### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/net.sf.VICE#10]
VICE icon seems to be [missing](https://flathub.org/repo/appstream/x86_64/icons/128x128/net.sf.VICE.C64.png) on Flathub and VICE seems to be missing in GNOME Software.

**Comment by digitalstreamio** [comment]
Thanks. I'll take a look at it this weekend and see if I can spin a new build.

**Comment by AsciiWolf** [comment]
Any news?

**Comment by digitalstreamio** [comment]
The issue is appdata points to

<launchable type="desktop-id">net.sf.VICE.C64.desktop</launchable>

which is used by Flathub to figure out which icon to use. Flathub default to the same name as the desktop id, so

https://flathub.org/repo/appstream/x86_64/icons/128x128/net.sf.VICE.C64.png

However, desktop file points to a different image since the image is reused between multiple entry points.

https://flathub.org/repo/appstream/x86_64/icons/128x128/net.sf.VICE.png

I take it Flathub doesn't actually read the desktop file so I guess a quick remedy would be to duplicate the image to make Flathub happy.

Does that sound ok?

**Comment by digitalstreamio** [comment]
@AsciiWolf   So I think there is a problem with either appdata guidelines or appstream-builder. Based on description provided on the wiki, appstream builder should have pulled the correct icon. This doesn't seem to be the case though. Any suggestions?

https://github.com/flathub/flathub/wiki/AppData-Guidelines

```
Basically describes how to launch this software. If a desktop file is linked, appstream-builder will pull data from it, namely categories and icons.

<launchable type="desktop-id">mscore.desktop</launchable>
```

**Comment by AsciiWolf** [comment]
Hmm, everything seems to be ok, but the icon is still not pulled for some reason. Sorry, I have no idea what could be wrong. :-/

**Comment by digitalstreamio** [comment]
@AsciiWolf I just reinstalled the app from Flathub and it seems that it is stilll referencing an old build. 

I can see that build bot completed the build. 

https://flathub.org/builds/#/builders/32/builds/417

Is there any additional step to commit it to the Flathub repo?

**Comment by digitalstreamio** [comment]
It seem the app was finally published into the Flathub repository. Any idea where the delay comes from? Build bots completed the build yesterday. Thx

**Comment by digitalstreamio** [comment]
@TingPing  Any thoughts on this issue? I opened a corresponding issue under flathub repo but haven't had much of a response yet.

**Comment by AsciiWolf** [comment]
The issue seems to be fixed. Thanks!
